wandb_version: 1

batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 500
learning_rate:
  desc: null
  value: 0.001
reg_factor:
  desc: null
  value: 0.001
seed:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    code_path: code/Sparse_Regression_42_Func/main.py
    python_version: 3.11.1
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708451892.219705
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.1
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
